---
title: "Git example"
output: word_document
---

# The basics of Git

## Introduction

NEW SECOND sentence from macbook pro. Git is a version control system. A NEW DIFFERENCE. This is inserted from macbook in the test_branch. FROM IMAC. It`s design to be used in the development of big software systems (the Linux kernel, ca. 1500 distributed developers). We will only use a tiny bit of the system, i.e. the most basic functionality. ANOTHER DIFFERENCE FROM IMAC. Some more just to be able to commit.

Adding some stuff from the macbook. Will also add a sentence to the paragraph above to try to force some conflict. I am now working on test_branch.

THIS IS ADDED FROM THE IMAC. I GUESS WE WILL GET SOME CONFLICT.

Do some editing on the branch.

MORE STUFF. THIS IS FROM THE MACPRO. 

JUST A LITTLE EDIT TO THE FILE BEFORE MERGING new_test_branch.

THIS IS ALSO FROM THE IMAC. ENTERING SOME NEW STUFF HERE.

Now we should be synced. Commit this and pull to the macbook pro before doing more work.

NOW I AM AT MASTER AN THE STUFF FROM `test_branch` IS MISSING. WILL COMMIT AND PUSH THIS FROM THE IMAC.

```
git config --global user.name "Arnstein Gjestland"
git config --global user.email "ag@hvl.no"
git config --global core.editor "nano -w"
```

Now I have switched to the `test_branch` and is working in this branch. The branch was created at the iMac. Time to commit this sentence. ADD A SENTENCE FROM THE IMAC AND COMMIT IT TO THE BRANCH.

```{r}
plot(cars)
```
Tester æ, ø og å.

TESTER Æ, Ø og Å.

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.


