---
title: "Git example"
output:
  word_document: default
  html_notebook: default
  pdf_document: default
editor_options:
  chunk_output_type: inline
---

# The basics of Git

## Introduction

OK to edit here?

New first sentence from macbook pro. Git is a version control system. A NEW DIFFERENCE FROM IMAC. It`s design to be used in the development of big software systems (the Linux kernel, ca. 1500 distributed developers). We will only use a tiny bit of the system, i.e. the most basic functionality. ANOTHER DIFFERENCE FROM IMAC. Some more just to be able to commit.

MORE STUFF. THIS IS FROM THE MACPRO.

THIS IS ALSO FROM THE IMAC. ENTERING SOME NEW STUFF HERE.

Now we should be synced. Commit this and pull to the macbook pro before doing more work.

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file). 

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.


